# Generated by Django 4.0.6 on 2022-07-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
